# Final Words {#Ch-Summary}

Research software continues to play an important role in enabling much of modern research. Without access to high quality research software, it would be impossible to address many pressing challenges we face, such as emerging infectious diseases, food security, wildfires, climate change, among others. Through numerous interactions with the US research community, we have identified several key challenges and solutions to improve the sustainability of research software and of those who develop and maintain it. This plan describes a cohesive set of interrelated activities to be coordinated and run by URSSI. 

Our goal is to improve the quality, usefulness, and sustainability of research software by improving practices, and increasing diversity of practitioners. To grow and sustain a thriving community around research software, we propose an institute to coordinate efforts around training and education, community development, software development practices, and advocating for people engaged in research software. Each of these four areas have activities designed to impact people, software, and the broader research software ecosystem.  These include impacts on:

**People**: Helping researchers develop their software skills, connecting them with peers, sharing best practices, preparing them for a workforce within and beyond academia, and getting recognition for their research software work as scholarship.

**Software**: Incubating promising research software tools and helping them become more sustainable, identifying challenges and developing resources to address them, disseminating best practices for software development

**Research Software ecosystem:** Incentivizing contribution to public infrastructure, recognizing and valuing software in academia, national labs, and industry, and increasing the diversity of research software practitioners in the United States.

The open science movement [@tennant_et_al_2020], which has seen growing support among early career researchers over the past decade, has surfaced many of the challenges facing research software. Among numerous motivations for greater openness, reproducibility, reusability and increased transparency rank high.  While the early days of the movement focused on open and free access to research publications, research data has been the more recent focus of the scholarly community. In addition to numerous data repositories, tools, and training resources, the community came together in 2013 to launch the Research Data Alliance, a community consortium whose mission is to improve cultural and technical practices for greater sharing of open data. 

Research software needs a coordinated effort of similar scale such as the one being led by the Research Software Alliance (https://www.researchsoft.org/). Many of the activities proposed in this plan are not entirely novel. However, they have never been carried out in a coordinated manner with the intention to develop and grow a community of researchers with a shared interest around research software.  A thriving community is also critical to address a challenge facing all of academia, national labs and industry, which is the lack of diversity. URSSI will be a platform to provide opportunities for many communities that have had little to no representation in this space.

While a handful of the activities we describe in this plan can be funded and executed independently, anything short of a coordinated effort will not have the impact we desire at the scales we describe. These activities are all interrelated and support each other. Therefore we are likely to have a substantially larger impact doing them in a coordinated fashion than as separate activities. An institute like URSSI can also serve as a focal point to coordinate many existing disparate efforts and help them succeed by reaching a wider audience. Addressing long standing systemic challenges requires a coordinated investment.

