on: [push]

name: combine-pdfs

jobs:
  combine_pdfs:
    runs-on: ubuntu-latest
    name: Combine PDFs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Combine PDFs
        id: combine
        uses: amoeba/combine-pdf-action@v1
        with:
          path: final
      - name: Upload combined pdf
        uses: actions/upload-artifact@v2
        with:
          name: combined-pdf
          path: final/combined.pdf

  - name: Deploy to Netlify
    if: contains(env.isExtPR, 'false')
    id: netlify-deploy
    uses: nwtgck/actions-netlify@v1.1
    with:
      publish-dir: './final'
      production-branch: master
      github-token: ${{ secrets.GITHUB_TOKEN }}
      deploy-message:
        'Deploy from GHA: ${{ github.event.pull_request.title || github.event.head_commit.message }} (${{ github.sha }})'
      # these all default to 'true'
      enable-pull-request-comment: false
      enable-commit-comment: false
    timeout-minutes: 1
